<?php
/**
 * IXTDataTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * IXTDataTypeEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IXTDataTypeEnum
{
    /**
     * Possible values of this enum
     */
    const STRING = 'string';
const ENUM = 'enum';
const NUMERIC = 'numeric';
const BOOLEAN = 'boolean';
const REFERENCE = 'reference';
const INTEGER = 'integer';
const DATETIME = 'datetime';
const DATE = 'date';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STRING,
self::ENUM,
self::NUMERIC,
self::BOOLEAN,
self::REFERENCE,
self::INTEGER,
self::DATETIME,
self::DATE,        ];
    }
}
