<?php
/**
 * IXTGovernmentIdTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * IXTGovernmentIdTypeEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IXTGovernmentIdTypeEnum
{
    /**
     * Possible values of this enum
     */
    const PASSPORT = 'passport';
const IDENTITY_CARD = 'identity_card';
const RESIDENT_PERMIT = 'resident_permit';
const BUSINESS_REGISTRATION = 'business_registration';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PASSPORT,
self::IDENTITY_CARD,
self::RESIDENT_PERMIT,
self::BUSINESS_REGISTRATION,        ];
    }
}
