<?php
/**
 * IXTInsuredRelationshipEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * IXTInsuredRelationshipEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IXTInsuredRelationshipEnum
{
    /**
     * Possible values of this enum
     */
    const OWN_ESTATE = 'own_estate';
const ENTITY = 'entity';
const OTHER_PERSON = 'other_person';
const SPOUSE = 'spouse';
const CHILD = 'child';
const PARENT = 'parent';
const GRANDCHILD = 'grandchild';
const GRANDPARENT = 'grandparent';
const SIBLING = 'sibling';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OWN_ESTATE,
self::ENTITY,
self::OTHER_PERSON,
self::SPOUSE,
self::CHILD,
self::PARENT,
self::GRANDCHILD,
self::GRANDPARENT,
self::SIBLING,        ];
    }
}
