<?php
/**
 * IXTSubscriberRelationshipEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * IXTSubscriberRelationshipEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IXTSubscriberRelationshipEnum
{
    /**
     * Possible values of this enum
     */
    const SELF = 'self';
const SPOUSE = 'spouse';
const CHILD = 'child';
const SIBLING = 'sibling';
const DOMESTIC_PARTNER = 'domestic_partner';
const PARENT = 'parent';
const GRANDPARENT = 'grandparent';
const GRANDCHILDREN = 'grandchildren';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SELF,
self::SPOUSE,
self::CHILD,
self::SIBLING,
self::DOMESTIC_PARTNER,
self::PARENT,
self::GRANDPARENT,
self::GRANDCHILDREN,        ];
    }
}
