<?php
/**
 * MotorbikeTypeNameEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MotorbikeTypeNameEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MotorbikeTypeNameEnum
{
    /**
     * Possible values of this enum
     */
    const ELECTRICAL = 'Electrical';
const THREE_WHEELER = 'ThreeWheeler';
const OVER50CC = 'Over50cc';
const UNDER50CC = 'Under50cc';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ELECTRICAL,
self::THREE_WHEELER,
self::OVER50CC,
self::UNDER50CC,        ];
    }
}
