<?php
/**
 * ApplicationPlanModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationPlanModelTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicationPlanModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationPlanModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationPlanModel"
     */
    public function testApplicationPlanModel()
    {
    }

    /**
     * Test attribute "underwriting_rules"
     */
    public function testPropertyUnderwritingRules()
    {
    }

    /**
     * Test attribute "underwriting_result"
     */
    public function testPropertyUnderwritingResult()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "plan_id"
     */
    public function testPropertyPlanId()
    {
    }

    /**
     * Test attribute "constraint_id"
     */
    public function testPropertyConstraintId()
    {
    }

    /**
     * Test attribute "constraint_name"
     */
    public function testPropertyConstraintName()
    {
    }

    /**
     * Test attribute "adjustment_amount"
     */
    public function testPropertyAdjustmentAmount()
    {
    }

    /**
     * Test attribute "adjustment_rate"
     */
    public function testPropertyAdjustmentRate()
    {
    }

    /**
     * Test attribute "payment_mode"
     */
    public function testPropertyPaymentMode()
    {
    }

    /**
     * Test attribute "insured_subjects"
     */
    public function testPropertyInsuredSubjects()
    {
    }

    /**
     * Test attribute "standard_premium"
     */
    public function testPropertyStandardPremium()
    {
    }

    /**
     * Test attribute "adjusted_premium"
     */
    public function testPropertyAdjustedPremium()
    {
    }

    /**
     * Test attribute "customized_attributes"
     */
    public function testPropertyCustomizedAttributes()
    {
    }
}
