<?php
/**
 * CreateApplicationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateApplicationModelTest Class Doc Comment
 *
 * @category    Class
 * @description CreateApplicationModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateApplicationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateApplicationModel"
     */
    public function testCreateApplicationModel()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "customized_attributes"
     */
    public function testPropertyCustomizedAttributes()
    {
    }

    /**
     * Test attribute "plans"
     */
    public function testPropertyPlans()
    {
    }

    /**
     * Test attribute "quotation_id"
     */
    public function testPropertyQuotationId()
    {
    }

    /**
     * Test attribute "constraint_id"
     */
    public function testPropertyConstraintId()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_data"
     */
    public function testPropertyClientData()
    {
    }

    /**
     * Test attribute "effected_at"
     */
    public function testPropertyEffectedAt()
    {
    }

    /**
     * Test attribute "purchased_at"
     */
    public function testPropertyPurchasedAt()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "applicant"
     */
    public function testPropertyApplicant()
    {
    }

    /**
     * Test attribute "beneficiaries"
     */
    public function testPropertyBeneficiaries()
    {
    }

    /**
     * Test attribute "policyholders"
     */
    public function testPropertyPolicyholders()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
