<?php
/**
 * DetailedApplicationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DetailedApplicationModelTest Class Doc Comment
 *
 * @category    Class
 * @description DetailedApplicationModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedApplicationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DetailedApplicationModel"
     */
    public function testDetailedApplicationModel()
    {
    }

    /**
     * Test attribute "underwriting_rules"
     */
    public function testPropertyUnderwritingRules()
    {
    }

    /**
     * Test attribute "underwriting_result"
     */
    public function testPropertyUnderwritingResult()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "quotation_id"
     */
    public function testPropertyQuotationId()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "member_id"
     */
    public function testPropertyMemberId()
    {
    }

    /**
     * Test attribute "constraint_id"
     */
    public function testPropertyConstraintId()
    {
    }

    /**
     * Test attribute "constraint_name"
     */
    public function testPropertyConstraintName()
    {
    }

    /**
     * Test attribute "application_type"
     */
    public function testPropertyApplicationType()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "plans"
     */
    public function testPropertyPlans()
    {
    }

    /**
     * Test attribute "applicant"
     */
    public function testPropertyApplicant()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_data"
     */
    public function testPropertyClientData()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "application_number"
     */
    public function testPropertyApplicationNumber()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "customized_attributes"
     */
    public function testPropertyCustomizedAttributes()
    {
    }

    /**
     * Test attribute "final_underwriting_result"
     */
    public function testPropertyFinalUnderwritingResult()
    {
    }

    /**
     * Test attribute "underwriter_underwriting_result"
     */
    public function testPropertyUnderwriterUnderwritingResult()
    {
    }

    /**
     * Test attribute "effected_at"
     */
    public function testPropertyEffectedAt()
    {
    }

    /**
     * Test attribute "purchased_at"
     */
    public function testPropertyPurchasedAt()
    {
    }

    /**
     * Test attribute "payment_period"
     */
    public function testPropertyPaymentPeriod()
    {
    }

    /**
     * Test attribute "beneficiary_sequences"
     */
    public function testPropertyBeneficiarySequences()
    {
    }

    /**
     * Test attribute "policyholders"
     */
    public function testPropertyPolicyholders()
    {
    }
}
