<?php
/**
 * DetailedPlanModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DetailedPlanModelTest Class Doc Comment
 *
 * @category    Class
 * @description DetailedPlanModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedPlanModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DetailedPlanModel"
     */
    public function testDetailedPlanModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "is_core"
     */
    public function testPropertyIsCore()
    {
    }

    /**
     * Test attribute "policy_period"
     */
    public function testPropertyPolicyPeriod()
    {
    }

    /**
     * Test attribute "payment_modes"
     */
    public function testPropertyPaymentModes()
    {
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
    }

    /**
     * Test attribute "benefits"
     */
    public function testPropertyBenefits()
    {
    }

    /**
     * Test attribute "insured_subject_constraints"
     */
    public function testPropertyInsuredSubjectConstraints()
    {
    }
}
