<?php
/**
 * UpdateApplicationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IXT-OKXE-Customer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateApplicationModelTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateApplicationModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateApplicationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateApplicationModel"
     */
    public function testUpdateApplicationModel()
    {
    }

    /**
     * Test attribute "client_data"
     */
    public function testPropertyClientData()
    {
    }

    /**
     * Test attribute "effected_at"
     */
    public function testPropertyEffectedAt()
    {
    }

    /**
     * Test attribute "customized_attributes"
     */
    public function testPropertyCustomizedAttributes()
    {
    }

    /**
     * Test attribute "plans"
     */
    public function testPropertyPlans()
    {
    }

    /**
     * Test attribute "applicant"
     */
    public function testPropertyApplicant()
    {
    }

    /**
     * Test attribute "beneficiaries"
     */
    public function testPropertyBeneficiaries()
    {
    }

    /**
     * Test attribute "policyholders"
     */
    public function testPropertyPolicyholders()
    {
    }
}
